### ISSUE TITLE
Any tricks for text embedding?

### ISSUE THREAD

**Issue by zsdonghao** [soumith/ganhacks#12]

**Comment by soumith** [comment]
text GANs are an open problem. Waiting for the first text GAN to be successful. No tricks ;)

**Comment by ethancaballero** [comment]
SeqGAN: Sequence Generative Adversarial Nets with Policy Gradient
https://github.com/LantaoYu/SeqGAN
https://arxiv.org/abs/1609.05473

**Comment by ethancaballero** [comment]
Improved Training of Wasserstein GANs
https://arxiv.org/abs/1704.00028
