### ISSUE TITLE
There is no source that has empirically demonstrated a positive effect of replay buffer on GAN training

### ISSUE THREAD

**Issue by AranKomat** [soumith/ganhacks#31]
I understand that the trick #8 "Use stability tricks from RL" is based on an actual paper. But other than the paper and this webpage, there's no source that has suggested experience replay for GAN. In the paper, it was only suggested it was reasonable to try it from the analogy, and so is it in this page. I would like to see an empirical evidence of the extent to which the GAN training benefits from keeping a replay buffer of past generations and occasionally showing them.

**Comment by ferumchrome** [comment]
I can remember only 1 paper, where authors demonstrated benefits of using buffer to update discriminator. Check "Learning from Simulated and Unsupervised Images through Adversarial Training" (https://arxiv.org/pdf/1612.07828).
