### ISSUE TITLE
Discriminator accuracy: 0.5 on average, but collapsed into 0 for negative samples and 1 for positive samples

### ISSUE THREAD

**Issue by danielegrattarola** [soumith/ganhacks#44]
I am monitoring the discriminator accuracy on separate batches for positive and negative samples as suggested in trick 4, but it often occurs the following situation:
- Average accuracy = 0.5 (average loss 0.69)
- Acc on negative samples = 0.0 (loss 0.69)
- Acc on positive samples = 1.0 (loss 0.7)

What could be the cause of this problem?

Cheers, 
Daniele

**Comment by jkim-** [comment]
It might mean that the discriminator is not powerful enough as it always outputs 1.  

Maybe try increasing its capacity?

**Comment by danielegrattarola** [comment]
Thanks for the reply @jkim- 
Turns out the discriminator was fine, but was simply producing values slightly higher than 0.5 for positive samples and slightly lower for negative ones. Since Keras automatically rounds predictions in order to compute accuracy, it was giving me that weird behavior.
