### ISSUE TITLE
Generator try to maximize, Discriminator try to minimize

### ISSUE THREAD

**Issue by Auth0rM0rgan** [soumith/ganhacks#49]
Hi, 
I am training a CycleGAN but the log file(Tensorbaord scalar) for both G and D is confusing to me.
As it written in the paper (Also, all the GAN papers), G aims to minimize the objective against an adversary D that tries to maximize it.

At the beginning of training, G is tried to minimize but after 60 epochs start to maximize also D is tried to maximize at the beginning and then start to minimize after epoch 60. I want to know the intuition behind of it. any idea?

should not model to minimize G and maximize D all the time, why after some epochs generators start to maximize and discriminator minimize?

Tensorboard scalar: [https://imgur.com/rdTxrUP](url)

Thanks in advance.

**Comment by adv-ai-tech** [comment]
No Idea
