### ISSUE TITLE
Question: Any interest in putting together a premium version for sale on SugarKubes?

### ISSUE THREAD

**Issue by wrannaman** [soumith/ganhacks#54]
Hi @soumith , congrats on the traction! Would you be interested in putting together a premium version of this repo to sell on [SugarKubes](https://sugarkubes.io)? It's a code and container marketplace I'm putting together.

**Comment by soumith** [comment]
no

**Comment by wrannaman** [comment]
got it! No worries!
Andrew Pierno <https://medium.com/@andrewpierno>
949.293.0435

**Comment by wrannaman** [comment]
fair enough, thanks for the response!

**Comment by wrannaman** [comment]
out of curiosity any particular reason why? Are you monetizing some other way?
